class AddressDetail{



List<String> regions = ["Addis Ababa","Afar Region","Amhara Region","Benishangul-Gumuz Region","Dire Dawa","Gambela Region","Harari Region","Oromia Region","Sidama Region","Somali Region","South West Ethiopia Peoples' Region","Southern Nations, Nationalities, and Peoples Region","Tigray Region"];
List<List<String>> Zone = [
  [
    'Addis Ketema',
  'Akaki-Kality',
  'Arada',
  'Bole',
  'Gulele',
  'Kirkos',
  'Kolfe Keranio',
  'Lideta',
  'Nifas Silk-Lafto',
  'Yeka',
  ], 
  [
  'Awsi Rasu',
  'Kilbet Rasu',
  'Gabi Rasu',
  'Fanti Rasu',
  'Hari Rasu',
  'Mahi Rasu',
  'Argobba',
],
[
  'Agew Awi',
  'East Gojjam',
  'North Gondar',
  'Central Gondar',
  'West Gondar',
  'Wag Hemra',
  'West Gojjam',
  'Bahir Dar',
  'West Gojjam',
  'South Gondar',
  'North Wollo',
  'South Wollo',
  'Oromia',
  'North Shewa',
],
[
  'Asosa',
  'Kamashi',
  'Metekel',
],
[],
[
  'Anywaa',
  'Majang',
  'Nuer',
],
[
  'Amir-Nur Woreda',
  'Abadir Woreda',
  'Shenkor Woreda',
  'Jin\'Eala Woreda',
  'Aboker Woreda',
  'Hakim Woreda',
  'Sofi Woreda',
  'Erer Woreda',
  'Dire-Teyara Woreda',
],
[
  'East Arsi',
  'West Arsi',
  'East Bale',
  'West Bale',
  'Borana',
  'East Hararghe',
  'East Shewa',
  'East Welega',
  'East Guji',
  'West Guji',
  'Horo Guduru Welega',
  'Illu Ababora',
  'Buno Bedele',
  'Jimma',
  'Kelam Welega',
  'North Shewa',
  'Southwest Shewa',
  'West Haraghe',
  'West Shewa',
  'West Welega',
  'Oromia Special Zone Surrounding Finfinne',
],
[],
[
  'Sitti Zone',
  'Fafan Zone',
  'Jarar Zone',
  'Erer Zone',
  'Nogob Zone',
  'Dollo Zone',
  'Korahe Zone',
  'Shabelle Zone',
  'Afder Zone',
  'Liben Zone',
  'Dhawa Zone',
  'Jigjiga Special Zone',
  'Tog Wajale Special Zone',
  'Degehabur Special Zone',
  'Gode Special Zone',
  'Kebri Beyah Special Zone',
  'Kebri Dahar Special Zone',
],
 [
  'Bench Maji',
  'Dawro',
  'Keffa',
  'Sheka',
  'Konta',
  'West Omo',
],
[
  'Gamo Gofa',
  'Gedeo',
  'Gurage',
  'Hadiya',
  'Kembata Tembaro',
  'Silt\'e',
  'South Omo',
  'Konso',
  'Wolayita',
  'Alaba',
  'Amaro',
  'Basketo',
  'Burji',
  'Dirashe',
  'Yem',
],
[
  'Central Tigray',
  'East Tigray',
  'North West Tigray',
  'South Tigray',
  'South East Tigray',
  'West Tigray',
  'Mekele',
]


];
}